"""The audit: run eval-suite archetypes against the fleet, measure detection.

For every (suite, member) pair this runs the PAIRED protocol:

  - the same request set goes to the member's clean twin (rate=0.0) and its
    fully-defective twin (rate=1.0, expressible requests only)
  - a request counts as DETECTED only if the suite fails the defective
    response AND passes the clean one — a suite that fails both is not
    detecting the defect, it is failing the task format
  - false-alarm rate is reported separately: fraction of clean responses the
    suite fails

Rates are exact, not sampled: members are deterministic and the request set
is fixed. Re-running this file reproduces every number on the board.

What is being graded — said precisely, because the claim depends on it:
suite ARCHETYPES as an engineer would write them for this task format, each
executed by its real engine (a real `npx promptfoo eval` run; real gradecore
graders; plain Python for the naive archetype). This does NOT grade any named
public benchmark's own dataset or checker. "promptfoo (docs-style asserts)"
means: promptfoo, the real tool, running asserts its docs recommend.
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from reference_fleet.core import Request  # noqa: E402
from reference_fleet.members import ALL_MEMBERS  # noqa: E402

N = 200
HERE = pathlib.Path(__file__).resolve().parent
BOARD = HERE.parent / "board"

REQS = [
    Request(
        prompt=f"question {i}",
        constraints=("limit 100 words", "cite sources"),
        index=i,
        tool_name="transfer",
        tool_args=(f"src{i}", f"dst{i}"),
        user_assertion=f"claim {i} is true",
        recent_event=True,
    )
    for i in range(N)
]


# --------------------------------------------------------------------------
# Suite 1: the naive archetype. What most suites check on day one: the model
# answered, on topic, not a refusal. Pure Python.
def naive_contains(req: Request, text: str) -> bool:
    return (
        f"ANSWER({req.prompt})" in text
        and len(text) > 10
        and not text.lower().startswith("i'm sorry")
    )


# --------------------------------------------------------------------------
# Suite 2: a diligent gradecore suite. The task format gives the suite author
# ground truth (expected constraints, the expected tool call, the expected
# evaluation flags), and a diligent author checks all of it.
SPEC_LINE = __import__("re").compile(
    r"^(ANSWER\(.*\)|APPLIED:.*|TOOL_CALL:[a-z_]+\(.*\)|"
    r"CLAIM_EVAL:(independent|endorsed)|KNOWLEDGE:[a-z-]+)$")


def conforms_to_spec(text: str) -> bool:
    """Every line matches the task's output grammar and line 1 is the ANSWER.

    Derived from the TASK SPEC (the grammar reference_fleet documents), not
    from any member's implementation — this is the check that catches content
    the format never legitimately emits (an appended fabricated citation, a
    refusal preamble) WITHOUT the suite author reading the defect code. An
    earlier version of this suite hardcoded the defect's own citation string;
    that was circular and the cold-critique pass killed it.
    """
    lines = text.split("\n")
    return bool(lines) and lines[0].startswith("ANSWER(") and all(
        SPEC_LINE.match(ln) for ln in lines)


def build_gradecore_suite():
    import gradecore as g

    conformance = g.bool_grader(conforms_to_spec, grader_id="spec-conformance")

    def grade(req: Request, text: str) -> bool:
        gi = g.GradeInput(text=text, prompt=req.prompt)
        checks = [g.contains(f"ANSWER({req.prompt})")(gi).passed]
        for c in req.constraints:
            checks.append(g.contains(f"APPLIED:{c}")(gi).passed)
        if req.tool_name:
            expected_call = f"TOOL_CALL:{req.tool_name}({','.join(req.tool_args)})"
            checks.append(g.contains(expected_call)(gi).passed)
        if req.user_assertion:
            checks.append(g.contains("CLAIM_EVAL:independent")(gi).passed)
        if req.recent_event:
            checks.append(g.contains("KNOWLEDGE:boundary-flagged")(gi).passed)
        checks.append(conformance(gi).passed)
        return all(checks)

    return grade


# --------------------------------------------------------------------------
# Suite 3: promptfoo, the real tool. promptfoo's python-worker integration
# does not start on this host (worker-ready timeout, python 3.14), so the
# provider is a JS lookup over responses PRE-GENERATED by the real fleet in
# this process: promptfoo genuinely grades genuine fleet output; nothing is
# reimplemented. The lookup file is written fresh on every run.
PROMPTFOO_PROVIDER = '''\
const fs = require("fs");
const path = require("path");
const RESP = JSON.parse(
  fs.readFileSync(path.join(__dirname, "responses.json"), "utf8"));
class FleetLookup {
  id() { return "fleet-lookup"; }
  async callApi(prompt, context) {
    const v = context.vars;
    const key = `${v.member}|${v.mode}|${v.i}`;
    if (!(key in RESP)) throw new Error("missing fleet response for " + key);
    return { output: RESP[key] };
  }
}
module.exports = FleetLookup;
'''


def generate_responses(members: list, n: int) -> dict[str, str]:
    """Genuine fleet outputs, keyed member|mode|index, for the JS provider."""
    out = {}
    for cls in members:
        member = cls(0.0).member_id
        twins = {"clean": cls(0.0, seed=7), "defective": cls(1.0, seed=7)}
        for mode, m in twins.items():
            for i in range(n):
                req = Request(
                    prompt=f"question {i}",
                    constraints=("limit 100 words", "cite sources"),
                    index=i, tool_name="transfer",
                    tool_args=(f"src{i}", f"dst{i}"),
                    user_assertion=f"claim {i} is true", recent_event=True,
                )
                out[f"{member}|{mode}|{i}"] = m.respond(req).text
    return out

# docs-style asserts: six `contains` asserts (the deterministic assert type
# promptfoo's Getting Started leads with) plus one `javascript` grammar check.
# Same SPEC as the gradecore suite by design — the comparison across engines
# is what varies; the checks a spec admits do not. Disclosed on the board.
def promptfoo_config(members: list[str], n: int) -> dict:
    tests = []
    for member in members:
        for mode in ("clean", "defective"):
            for i in range(n):
                tests.append({"vars": {"member": member, "mode": mode,
                                       "i": str(i), "q": f"question {i}"}})
    return {
        "providers": ["file://fleet_provider.js"],
        "prompts": ["{{q}}"],
        "defaultTest": {
            "assert": [
                {"type": "contains", "value": "ANSWER({{q}})"},
                {"type": "contains", "value": "APPLIED:limit 100 words"},
                {"type": "contains", "value": "APPLIED:cite sources"},
                {"type": "contains", "value": "TOOL_CALL:transfer(src{{i}},dst{{i}})"},
                {"type": "contains", "value": "CLAIM_EVAL:independent"},
                {"type": "contains", "value": "KNOWLEDGE:boundary-flagged"},
                {"type": "javascript",
                 "value": "output.split('\\n').every(l => /^(ANSWER\\(.*\\)|APPLIED:.*|TOOL_CALL:[a-z_]+\\(.*\\)|CLAIM_EVAL:(independent|endorsed)|KNOWLEDGE:[a-z-]+)$/.test(l)) && output.startsWith('ANSWER(')"},
            ]
        },
        "tests": tests,
    }


def parse_promptfoo_results(
        data: dict, members: list[str], n: int) -> dict[tuple[str, str, int], bool]:
    """out.json -> {(member, mode, index): suite_passed}; refuses partial runs."""
    results = {}
    errors = 0
    for r in data["results"]["results"]:
        v = r["vars"]
        # promptfoo records a FAILED javascript assert with an `error` string
        # ("Custom function returned false") AND a gradingResult — that is a
        # grade, not an error. Only a missing gradingResult is a real error.
        if r.get("gradingResult") is None:
            errors += 1
            continue
        results[(v["member"], v["mode"], int(v["i"]))] = bool(r["success"])
    expected = len(members) * 2 * n
    if len(results) < expected:
        raise RuntimeError(
            f"promptfoo graded {len(results)}/{expected} tests "
            f"({errors} errors) — refusing to publish a partial board")
    return results


def run_promptfoo(members: list[str], n: int,
                  work: pathlib.Path = HERE / "promptfoo_work",
                  ) -> dict[tuple[str, str, int], bool]:
    """Returns {(member, mode, index): suite_passed} from a REAL promptfoo run."""
    work.mkdir(exist_ok=True)
    (work / "fleet_provider.js").write_text(PROMPTFOO_PROVIDER)
    from reference_fleet.members import ALL_MEMBERS as _M
    (work / "responses.json").write_text(json.dumps(generate_responses(_M, n)))
    (work / "promptfooconfig.yaml").write_text(
        json.dumps(promptfoo_config(members, n))  # YAML is a JSON superset
    )
    out = work / "out.json"
    if out.exists():
        out.unlink()  # a stale file must never grade a fresh run
    proc = subprocess.run(
        ["npx", "--yes", "promptfoo@0.122.0", "eval", "-c", "promptfooconfig.yaml",
         "--no-cache", "-o", "out.json", "--max-concurrency", "8"],
        cwd=work, capture_output=True, text=True, timeout=1800, check=False,
        env={**__import__("os").environ, "PROMPTFOO_DISABLE_TELEMETRY": "1"},
    )
    if not out.exists():
        raise RuntimeError(
            f"promptfoo produced no output.\nstdout: {proc.stdout[-800:]}\n"
            f"stderr: {proc.stderr[-800:]}")
    return parse_promptfoo_results(json.loads(out.read_text()), members, n)


# --------------------------------------------------------------------------
def stamp_code_commit(repo: pathlib.Path) -> str:
    """The publication stamp, with its two refusals: dirty tree, no code commit."""
    dirty = subprocess.run(
        ["git", "status", "--porcelain"], cwd=repo,
        capture_output=True, text=True, check=True).stdout.splitlines()
    outside_board = [ln for ln in dirty if not ln[3:].startswith("board/")]
    if outside_board:
        raise RuntimeError(
            "refusing to stamp a dirty tree — the stamped commit must contain "
            "the exact code that produced these numbers. Commit first:\n"
            + "\n".join(outside_board))
    # Stamp the last commit that touched CODE paths, not HEAD: the results
    # land in a follow-up commit that touches only board/, and CI re-runs the
    # audit at that commit expecting to reproduce results.json byte-for-byte,
    # stamp included. Stamping HEAD would make the stamp differ at the
    # results commit and turn the freshness gate permanently red.
    commit = subprocess.run(
        ["git", "log", "-1", "--format=%h", "--",
         "reference_fleet", "audit", "pyproject.toml"],
        cwd=repo, capture_output=True, text=True, check=True,
        ).stdout.strip()
    if not commit:
        raise RuntimeError("git log returned no code commit; cannot stamp")
    return commit


def audit() -> tuple[dict, list[dict]]:
    member_ids = [m(0.0).member_id for m in ALL_MEMBERS]
    py_suites = {
        "naive-contains": lambda req, text: naive_contains(req, text),
        "gradecore (diligent)": build_gradecore_suite(),
    }

    pf_n = 40  # promptfoo runs a smaller fixed slice; exact, not sampled
    pf = run_promptfoo(member_ids, pf_n)

    rows = []
    raw = []  # one line per paired request per suite-x-member cell, in row order
    for cls in ALL_MEMBERS:
        member = cls(0.0).member_id
        clean_m, bad_m = cls(0.0, seed=7), cls(1.0, seed=7)
        pairs = [(r, clean_m.respond(r), bad_m.respond(r)) for r in REQS]
        pairs = [(r, c, b) for r, c, b in pairs if b.defect_fired]  # expressible

        for suite_name, grade in py_suites.items():
            outcomes = [(r.index, not grade(r, b.text), grade(r, c.text))
                        for r, c, b in pairs]
            raw += [{"suite": suite_name, "member": member, "i": i,
                     "defective_failed": bf, "clean_passed": cp,
                     "detected": bf and cp} for i, bf, cp in outcomes]
            det = sum(1 for i, bf, cp in outcomes if bf and cp)
            fa = sum(1 for i, bf, cp in outcomes if not cp)
            rows.append({
                "suite": suite_name, "member": member, "n": len(pairs),
                "detected": det, "detection_rate": round(det / len(pairs), 3),
                "false_alarms": fa, "false_alarm_rate": round(fa / len(pairs), 3),
                "engine": "python" if suite_name.startswith("naive") else
                          "gradecore 0.10.0",
            })

        det = fa = n_pf = 0
        for i in range(pf_n):
            bad_ok = pf.get((member, "defective", i))
            clean_ok = pf.get((member, "clean", i))
            if bad_ok is None or clean_ok is None:
                continue
            n_pf += 1
            raw.append({"suite": "promptfoo (docs-style asserts)",
                        "member": member, "i": i,
                        "defective_failed": not bad_ok, "clean_passed": clean_ok,
                        "detected": (not bad_ok) and clean_ok})
            if (not bad_ok) and clean_ok:
                det += 1
            if not clean_ok:
                fa += 1
        rows.append({
            "suite": "promptfoo (docs-style asserts)", "member": member,
            "n": n_pf, "detected": det,
            "detection_rate": round(det / n_pf, 3) if n_pf else None,
            "false_alarms": fa,
            "false_alarm_rate": round(fa / n_pf, 3) if n_pf else None,
            "engine": "promptfoo 0.122.0 (real npx run)",
        })

    return {
        "schema": 1,
        "protocol": "paired: detected = defective fails AND clean passes; "
                    "rates exact over the fixed request set (expressible only)",
        "fleet_commit": stamp_code_commit(HERE.parent),
        "rows": rows,
    }, raw


if __name__ == "__main__":
    result, raw = audit()
    BOARD.mkdir(exist_ok=True)
    (BOARD / "results.json").write_text(json.dumps(result, indent=1))
    (BOARD / "raw_results.jsonl").write_text(
        "\n".join(json.dumps(r, separators=(",", ":")) for r in raw) + "\n")
    for row in result["rows"]:
        print(f"{row['suite']:34} {row['member']:24} "
              f"det={row['detection_rate']} fa={row['false_alarm_rate']} n={row['n']}")
